wallet_sync_interval: 30s
tx_block_interval: 1h
tx_pool_flush_interval: 15s

postgres:
  host: localhost
  port: 5432
  user: mfreelance
  password: yourpassword091928374654ikd83km
  db: mfreelance

redis:
  host: 127.0.0.1
  port: 6379
  password: ""

jwt:
  token: supersecrettoken123

server:
  port: 9999
  listen_addr: 127.0.0.1

electrum:
  host: 127.0.0.1
  port: 7777
  user: Electrum
  password: Electrum

monero:
  host: 127.0.0.1
  port: 28088
  user: monero
  password: rpcPassword
  address: 9w49jr2CCtHcYkaVpwMX29Sq6AdnRXNTsZv85WWqwzCQYKmdF3ZggaiisJMFtci8LTBRNKkwpMfQ9g2qMMwr4De16Es8F4M
  commission: 5

bitcoin:
  address: tb1q4zue4uyep4dgx96erac2ey3efdw2q6537wh3j7
  commission: 25

max:
  profiles: 120
  avatar_size_mb: 2
  addr_per_block: 100

tasks:
  min_interval: 1h
  duplicate_window: 24h
  rate_limit_disabled: false
min_transaction_amount: 0

captcha:
  enabled: true
  rate_limit_per_minute: 10
  rate_limit_per_hour: 100
  font_path: "./fonts/captchaFont.ttf"

